In [131]:


# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sb
from pandas.plotting import scatter_matrix

# Machine Learning Algorithms
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

# Model Selection and Evaluation
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

# Performance
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# For Missing Values
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

In [132]:
import pandas as pd
#mat plot
import matplotlib.pyplot as plt
#Sea born
import seaborn as sns
#Num py
import numpy as np
#Sk learn imports
from sklearn import tree,preprocessing
#ensembles
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier
import sklearn.metrics as metrics
#scores
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,roc_auc_score,auc  
#models
from sklearn.model_selection import StratifiedKFold,train_test_split,cross_val_score,learning_curve,GridSearchCV,validation_curve
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
# import xgboost as xgb
#export the model
import pickle
import os
import warnings

In [133]:
fifa_raw_dataset = pd.read_csv('/Users/heleerana/Desktop/1 python project/footballFIFA19.csv')

In [134]:
fifa_raw_dataset.head()

,Unnamed: 0,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [135]:
fifa_raw_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 85 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   ID                        18207 non-null  int64
 2   Name                      18207 non-null  object
 3   Age                       18207 non-null  int64
 4   Nationality               18207 non-null  object
 5   Overall                   18207 non-null  int64
 6   Potential                 18207 non-null  int64
 7   Club                      17966 non-null  object
 8   Value                     18207 non-null  object
 9   Wage                      18207 non-null  object
 10  Special                   18207 non-null  int64
 11  Preferred Foot            18159 non-null  object
 12  International Reputation  18159 non-null  float64
 13  Weak Foot                 18159 non-null  float64
 14  Skill Moves               18159 non-null  float64
 15  Work Rate                 18159 non-null  object
 16  Body Type                 18159 non-null  object
 17  Real Face                 18159 non-null  object
 18  Position                  18147 non-null  object
 19  Jersey Number             18147 non-null  float64
 20  Joined                    16654 non-null  object
 21  Contract Valid Until      17918 non-null  object
 22  Height                    18159 non-null  object
 23  Weight                    18159 non-null  object
 24  LS                        16122 non-null  object
 25  ST                        16122 non-null  object
 26  RS                        16122 non-null  object
 27  LW                        16122 non-null  object
 28  LF                        16122 non-null  object
 29  CF                        16122 non-null  object
 30  RF                        16122 non-null  object
 31  RW                        16122 non-null  object
 32  LAM                       16122 non-null  object
 33  CAM                       16122 non-null  object
 34  RAM                       16122 non-null  object
 35  LM                        16122 non-null  object
 36  LCM                       16122 non-null  object
 37  CM                        16122 non-null  object
 38  RCM                       16122 non-null  object
 39  RM                        16122 non-null  object
 40  LWB                       16122 non-null  object
 41  LDM                       16122 non-null  object
 42  CDM                       16122 non-null  object
 43  RDM                       16122 non-null  object
 44  RWB                       16122 non-null  object
 45  LB                        16122 non-null  object
 46  LCB                       16122 non-null  object
 47  CB                        16122 non-null  object
 48  RCB                       16122 non-null  object
 49  RB                        16122 non-null  object
 50  Crossing                  18159 non-null  float64
 51  Finishing                 18159 non-null  float64
 52  HeadingAccuracy           18159 non-null  float64
 53  ShortPassing              18159 non-null  float64
 54  Volleys                   18159 non-null  float64
 55  Dribbling                 18159 non-null  float64
 56  Curve                     18159 non-null  float64
 57  FKAccuracy                18159 non-null  float64
 58  LongPassing               18159 non-null  float64
 59  BallControl               18159 non-null  float64
 60  Acceleration              18159 non-null  float64
 61  SprintSpeed               18159 non-null  float64
 62  Agility                   18159 non-null  float64
 63  Reactions                 18159 non-null  float64
 64  Balance                   18159 non-null  float64
 65  ShotPower                 18159 non-null  float64
 66  Jumping                   18159 non-null  float64
 67  Stamina                   18159 non-null  float64
 68  Strength                  18159 non-null  float64
 69  LongShots                 18159 non-null  float64
 70  Aggression                18159 non-null  float64
 71  Interceptions             18159 non-null  float64
 72  Positioning               18159 non-null  float64
 73  Vision                    18159 non-null  float64
 74  Penalties                 18159 non-null  float64
 75  Composure                 18159 non-null  float64
 76  Marking                   18159 non-null  float64
 77  StandingTackle            18159 non-null  float64
 78  SlidingTackle             18159 non-null  float64
 79  GKDiving                  18159 non-null  float64
 80  GKHandling                18159 non-null  float64
 81  GKKicking                 18159 non-null  float64
 82  GKPositioning             18159 non-null  float64
 83  GKReflexes                18159 non-null  float64
 84  Release Clause            16643 non-null  object
dtypes: float64(38), int64(6), object(41)
memory usage: 11.8+ MB

In [136]:
fifa_raw_dataset.shape

(18207, 85)

# Feature Selection

In [137]:
features = ['International Reputation','Crossing','Finishing','ShortPassing','FKAccuracy', 'Balance','Strength','StandingTackle', 'SlidingTackle', 'Overall', 'Weak Foot','Skill Moves','Potential', 'Composure', ]
fifa_dataset = fifa_raw_dataset[[*features]]
fifa_dataset.head()

,International Reputation,Crossing,Finishing,ShortPassing,FKAccuracy,Balance,Strength,StandingTackle,SlidingTackle,Overall,Weak Foot,Skill Moves,Potential,Composure
0,5.0,84.0,95.0,90.0,94.0,95.0,59.0,28.0,26.0,94,4.0,4.0,94,96.0
1,5.0,84.0,94.0,81.0,76.0,70.0,79.0,31.0,23.0,94,4.0,5.0,94,95.0
2,5.0,79.0,87.0,84.0,87.0,84.0,49.0,24.0,33.0,92,5.0,5.0,93,94.0
3,4.0,17.0,13.0,50.0,19.0,43.0,64.0,21.0,13.0,91,3.0,1.0,93,68.0
4,4.0,93.0,82.0,92.0,83.0,77.0,75.0,58.0,51.0,91,5.0,4.0,92,88.0

In [138]:
fifa_dataset.shape

(18207, 14)

# Data preprocessing

In [139]:
fifa_dataset['International Reputation'].fillna(fifa_dataset['International Reputation'].mean(), inplace = True)
fifa_dataset['Crossing'].fillna(fifa_dataset['Crossing'].mean(), inplace = True)
fifa_dataset['Finishing'].fillna(fifa_dataset['Finishing'].mean(), inplace = True)
fifa_dataset['ShortPassing'].fillna(fifa_dataset['ShortPassing'].mean(), inplace = True)
fifa_dataset['FKAccuracy'].fillna(fifa_dataset['FKAccuracy'].mean(), inplace = True)
fifa_dataset['Balance'].fillna(fifa_dataset['Balance'].mean(), inplace = True)
fifa_dataset['Strength'].fillna(fifa_dataset['Strength'].mean(), inplace = True)
fifa_dataset['Crossing'].fillna(fifa_dataset['Crossing'].mean(), inplace = True)
fifa_dataset['StandingTackle'].fillna(fifa_dataset['StandingTackle'].mean(), inplace = True)
fifa_dataset['SlidingTackle'].fillna(fifa_dataset['SlidingTackle'].mean(), inplace = True)
fifa_dataset['Composure'].fillna(fifa_dataset['Composure'].mean(), inplace = True)
fifa_dataset['Overall'].fillna(fifa_dataset['Overall'].mean(), inplace = True)
fifa_dataset['Weak Foot'].fillna(fifa_dataset['Weak Foot'].mean(), inplace = True)
fifa_dataset['Skill Moves'].fillna(fifa_dataset['Skill Moves'].mean(), inplace = True)
fifa_dataset['Potential'].fillna(fifa_dataset['Potential'].mean(), inplace = True)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [140]:
fifa_dataset.isnull().sum()

International Reputation    0
Crossing                    0
Finishing                   0
ShortPassing                0
FKAccuracy                  0
Balance                     0
Strength                    0
StandingTackle              0
SlidingTackle               0
Overall                     0
Weak Foot                   0
Skill Moves                 0
Potential                   0
Composure                   0
dtype: int64

In [141]:
df = fifa_dataset.astype(int)
# df = df["col1"].astype(int)

In [142]:
df

,International Reputation,Crossing,Finishing,ShortPassing,FKAccuracy,Balance,Strength,StandingTackle,SlidingTackle,Overall,Weak Foot,Skill Moves,Potential,Composure
0,5,84,95,90,94,95,59,28,26,94,4,4,94,96
1,5,84,94,81,76,70,79,31,23,94,4,5,94,95
2,5,79,87,84,87,84,49,24,33,92,5,5,93,94
3,4,17,13,50,19,43,64,21,13,91,3,1,93,68
4,4,93,82,92,83,77,75,58,51,91,5,4,92,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,1,34,38,49,34,76,47,48,47,47,2,2,65,45
18203,1,23,52,43,20,52,67,15,19,47,2,2,63,42
18204,1,25,40,38,27,58,32,13,11,47,3,2,67,41
18205,1,44,50,42,32,71,48,25,27,47,3,2,66,46
18206,1,41,34,48,34,63,60,43,50,46,3,2,66,43

In [143]:
bins = [0, 50, 75, 100]
group_names = ['low', 'medium', 'high']
df['Overall'] = pd.cut(df['Overall'], bins, labels=group_names)
print (df)

       International Reputation  Crossing  Finishing  ShortPassing  \
0                             5        84         95            90
1                             5        84         94            81
2                             5        79         87            84
3                             4        17         13            50
4                             4        93         82            92
...                         ...       ...        ...           ...
18202                         1        34         38            49
18203                         1        23         52            43
18204                         1        25         40            38
18205                         1        44         50            42
18206                         1        41         34            48

       FKAccuracy  Balance  Strength  StandingTackle  SlidingTackle Overall  \
0              94       95        59              28             26    high
1              76       70        79              31             23    high
2              87       84        49              24             33    high
3              19       43        64              21             13    high
4              83       77        75              58             51    high
...           ...      ...       ...             ...            ...     ...
18202          34       76        47              48             47     low
18203          20       52        67              15             19     low
18204          27       58        32              13             11     low
18205          32       71        48              25             27     low
18206          34       63        60              43             50     low

       Weak Foot  Skill Moves  Potential  Composure
0              4            4         94         96
1              4            5         94         95
2              5            5         93         94
3              3            1         93         68
4              5            4         92         88
...          ...          ...        ...        ...
18202          2            2         65         45
18203          2            2         63         42
18204          3            2         67         41
18205          3            2         66         46
18206          3            2         66         43

[18207 rows x 14 columns]

# Dividing the data into Test and Train set

In [144]:
#The Y feature is the overall column
y = df["Overall"]

#The other features are all but the overall
df.drop(columns=["Overall"],inplace=True)

In [145]:
X_train_dev, X_test, y_train_dev, y_test = train_test_split(df, y, 
                                                    test_size=0.20, 
                                                    random_state=42 )